package toliner.showblockresistance

import net.minecraftforge.fml.common.Mod
import net.minecraftforge.fml.common.ModMetadata
import net.minecraftforge.fml.common.event.FMLInitializationEvent
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent


@Mod(modid = MOD_ID, name = MOD_NAME, version = VERSION, useMetadata = true)
class ShowBlockResistanceModCore {
    companion object {
        @JvmStatic
        @Mod.Instance
        lateinit var INSTANCE: ShowBlockResistanceModCore

        @JvmStatic
        @Mod.Metadata
        lateinit var META: ModMetadata
    }

    @Mod.EventHandler
    fun preinit(event: FMLPreInitializationEvent) {
        loadMeta()
        //register()
        //Registry.preinit(event)
        /*
        if(event.side.isClient) {
            texture()
        }
        */
    }

    @Mod.EventHandler
    fun init(event: FMLInitializationEvent) {
        //recipe()
    }

    @Mod.EventHandler
    fun postinit(event: FMLPostInitializationEvent) {

    }

    private fun loadMeta() {
        META.modId = MOD_ID
        META.name = MOD_NAME
        META.version = VERSION
        META.authorList.add("toliner")
        //META.url = "http://minecraft.curseforge.com/projects/$MOD_ID"
        META.autogenerated = false
    }
}